stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipelines/stage01_data_ingestion.py
    deps: 
      - src/cnnClassifier/pipelines/stage01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data


  prepare_base_model:
    cmd: python src/cnnClassifier/pipelines/stage02_prepare_base_model.py
    deps: 
      - src/cnnClassifier/pipelines/stage02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  model_trainer:
    cmd: python src/cnnClassifier/pipelines/stage03_model_trainer.py
    deps: 
      - src/cnnClassifier/pipelines/stage03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

    
  model_evaluation:
    cmd: python src/cnnClassifier/pipelines/stage04_model_evaluation_mlflow.py
    deps: 
      - src/cnnClassifier/pipelines/stage04_model_evaluation_mlflow.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: False
